site:
  title: 'Title'
copyright:
  label: '&copy; 2014 name'
  url: 'http://example.com/'
#footer_links:
#  - label_ruby: "t('.feed')"
#    url_ruby: 'posts_path(format: :atom)'
#  - label: 'Special Thanks'
#    url_ruby: 'main_app.thanks_path'
exception_notification:
  prefix: '[Blog] '
  sender: '"notifier" <notifier@example.com>'
  recipients: 
    - 'recipient@example.com'
tweet:
  prefix: 'New post'
  suffix: '@tnantoka'
